add simplified Chinese readme
canonical/dqlite pull request #421
Opened 2022-10-27 10:57 UTC by growdu

2022-10-27 11:11 UTC, MathieuBordere commented
@adglkh can you do a quick check please?

2022-10-28 03:36 UTC, adglkh requested changes
Overall, it looks great.
Just a few minor comments.

2022-10-28 03:36 UTC, adglkh commented on README_CH.md
> +“dqlite”是“distributed SQLite”的简写，即分布式sqlite。
“dqlite”是“distributed SQLite”的简写，即分布式sqlite。
 ->
“dqlite”是“distributed SQLite”的简写，即分布式SQLite。意味着dqlite通过网络协议扩展SQLite，将应用程序的各个实例连接在一起，让它们作为一个高可用的集群，而不依赖外部数据库。

2022-10-28 03:36 UTC, adglkh commented on README_CH.md
> +- 针对 SQLite 原语和数据类型优化过后的自定义网络协议
针对 SQLite 原语和数据类型优化过后的自定义网络协议
->
针对SQLite 原始数据类型优化的自定义网络协议

2022-10-28 03:36 UTC, adglkh commented on README_CH.md
> +- 基于[Raft](https://raft.github.io/)协议的数据流复制和高效的[C-raft](https://github.com/canonical/raft)实现
基于[Raft](https://raft.github.io/)协议的数据流复制和高效的[C-raft](https://github.com/canonical/raft)实现
->
基于[Raft](https://raft.github.io/)算法的数据复制及其高效[C-raft](https://github.com/canonical/raft)实现

2022-10-28 03:36 UTC, adglkh commented on README_CH.md
> +I/O](https://man7.org/linux/man-pages/man2/io_setup.2.html) 的内核（注意与[POSIX AIO](https://man7.org/linux/man-pages/man7/aio.7.html) 不是同一个），因为 C-raft 的 libuv 后端会使用。
dqlite 在 Linux 上运行，需要一个支持 [native async
I/O](https://man7.org/linux/man-pages/man2/io_setup.2.html) 的内核（注意与[POSIX AIO](https://man7.org/linux/man-pages/man7/aio.7.html) 不是同一个），因为 C-raft 的 libuv 后端会使用。
->
dqlite 在 Linux 上运行，由于C-raft 的 libuv 后端的实现，需要一个支持 [native async
I/O](https://man7.org/linux/man-pages/man2/io_setup.2.html) 的内核(注意不要和[POSIX AIO](https://man7.org/linux/man-pages/man7/aio.7.html)混淆)。

2022-10-28 03:36 UTC, adglkh commented on README_CH.md
> +在 FOSDEM 2020 上发表了关于 dqlite 的演讲视频，您可以在[此处](https://fosdem.org/2020/schedule/event/dqlite/)观看。
在 FOSDEM 2020 上发表了关于 dqlite 的演讲视频，
 ->
在 FOSDEM 2020 上有一个关于dqlite的演讲视频,

2022-10-28 03:36 UTC, adglkh commented on README_CH.md
> +您的linux发行版应该已经为您提供了预构建的 libuv 库和 libsqlite3-dev,就不需要在下载了，否则还需要下载这两个依赖。
提供了预构建的 libuv 库
->
提供了预构建的 libuv 共享库

2022-10-28 13:20 UTC, growdu commented
> Overall, it looks great. Just a few minor comments.

I fixed these，thanks a lot.

2022-10-28 14:05 UTC, adglkh approved these changes
LGTM. Thanks!

2022-10-28 14:07 UTC, merged